config:
  client_id: <insert_id_here>
  client_secret: <insert_secret_here>
  redirect_url: <insert_url_here>

  discover_weekly_id: <insert_id_here>
  discover_save_id: <insert_id_here>

  concert_playlist_id: <insert_id_here>
  output_file_path: <insert_path_here>