spotify:
  client_id: <insert_id_here>
  client_secret: <insert_secret_here>
  redirect_url: <insert_url_here>
  concert_playlist_id: <insert_id_here>

seatgeek:
  client_id: <insert_id_here>
  client_secret: <insert_secret_here>
  state_id: AZ
  
  output_file_path: output_file_here
  manual_artists:
    - insert_here
